# Generated by Django 5.1.1 on 2024-09-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('price_list', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('curr', models.CharField(max_length=10)),
            ],
        ),
    ]
