# Generated by Django 5.1.1 on 2024-09-12 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="brand_id",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="price",
            name="curr",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AlterField(
            model_name="price",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="price_list",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="price",
            name="priority",
            field=models.PositiveIntegerField(
                choices=[(0, "Baja"), (1, "Alta")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="product_id",
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name="price",
            index=models.Index(
                fields=["product_id", "brand_id", "price_list"],
                name="prices_pric_product_693c7c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="price",
            constraint=models.UniqueConstraint(
                fields=("product_id", "brand_id", "price_list"),
                name="unique_price_for_brand_and_list",
            ),
        ),
        migrations.AddConstraint(
            model_name="price",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gte", 0)), name="price_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="price",
            constraint=models.CheckConstraint(
                condition=models.Q(("start_date__lt", models.F("end_date"))),
                name="valid_date_range",
            ),
        ),
    ]
