# Generated by Django 5.1.1 on 2024-09-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prices", "0003_remove_price_curr"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="curr",
            field=models.CharField(default="USD", max_length=3),
        ),
    ]
